### ISSUE TITLE
How  is  this  project made？

### ISSUE THREAD

**Issue by dbsxdbsx** [exceljs/exceljs#1110]
I see that the project is wrote in js.  But I am not familiar with js.  I wonder how excel  is controlled here.   I personally tried using COM object through c++. But I got trouble in finding proper interfaces.  Does this project take the same way?

**Comment by Tilogorn** [comment]
A .xlsx file is basically a zipped archive full of xml-files (among others, like media files). You can implement XLSX export and import from basically any programming language as long as you are capable of implementing the xlsx spec because it is "just reading and writing plain text files" (of course it is super complex, just simplified for your understanding).

**Comment by Siemienik** [comment]
@dbsxdbsx `exceljs` actually doesn't handle Excel app, 

This lib has two main layers:
1. Reader/Write - which operate on xml files included in xlsx: https://github.com/exceljs/exceljs/tree/master/lib/xlsx/xform

2. Logic layer - has implemented logic of objects existed in xlsx file (Workbook, worksheet etc.) 
https://github.com/exceljs/exceljs/tree/master/lib/doc

It's possible because xlsx file it's _- as @Tilogorn said -_ a simple ZIP file (You can change the file's extension from .xlsx to .zip and unpack it :) )

**Comment by dbsxdbsx** [comment]
Thanks!
