### ISSUE TITLE
[BUG] getColumn().width doesnt return correct value

### ISSUE THREAD

**Issue by TranBaVinhSon** [exceljs/exceljs#1161]
## 🐛 Bug Report

Lib version: 3.8.0

## Steps To Reproduce

In my excel, the 2th column width is 34.86 (character counts) but when I use Exceljs to get that column width, it returned `35.5703125`.
Please take a look at my file and code.
```javascript
const ExcelJS = require("exceljs");
const workbook = await new ExcelJS.Workbook().xlsx.readFile("test.xlsx");
const worksheet = workbook.worksheets[0];
console.log(worksheet.getRow(3).height);
console.log(worksheet.getColumn(2).width); // should return 34.86
```

[test.xlsx](https://github.com/exceljs/exceljs/files/4315734/test.xlsx)

And sometimes`getRow().height` returns `undefined` depends on the index of row. Is this a bug of exceljs ?
## The expected behaviour:
- `getColumn(2).width` should return correct value
- `getRow().height` should not return undefined

**Comment by Alanscut** [comment]
- the differences is not an issue of exceljs, this is caused by the computed way of width and height, it is related to resolution. when you rename your excel file to `xxx.zip`, then unzip it, find the `sheet1.xml`, you will find that the real width is `35.5703125` but not `34.86 ` which show in excel. Exceljs just returned the real value of excel file, but not change it.

- when not set row height, then get the global default row height:
```
worksheet3.properties.defaultRowHeight
```

**Comment by Siemienik** [comment]
excel js provide width and height in pixels.
character count is an additional solution to Excel.
