### ISSUE TITLE
[BUG] 'unexpected close tag' error when trying to read *.xlsm files

### ISSUE THREAD

**Issue by vanyadymousky** [exceljs/exceljs#1316]
## 🐛 Bug Report

Hello! 
Upgraded to 3.10.0 occasionally (was ^3.9.0) and when trying to read ***.xlsm** files I got '**unexpected close tag**' error. Was not able to track where it goes from the sources.

Lib version: 3.10.0 / 4.0.0

## Steps To Reproduce

Reading file from a array buffer like this: 
```javascript
async (buffer: ArrayBuffer) => {
  const workbook = new Excel.Workbook();
  await workbook.xlsx.load(buffer);
  return workbook;
}
```

Then iterating workbook things like this:
```javascript
workbook.eachSheet(sheet => {
  sheet.eachRow(row => {
    row.eachCell((cell: Cell) => {
```

## The expected behaviour:

As it was before, xlsm file got read and saved.

**Comment by vincepunkrock** [comment]
Did you manage to fix this problem?

**Comment by vanyadymousky** [comment]
@vincepunkrock Hey! No. Switched to different library - SheetJS

**Comment by vincepunkrock** [comment]
@vanyadymousky Ok thank you for the info. With SheetJS I had the problem that styles and format aren't kept in the community version.

**Comment by vanyadymousky** [comment]
@vincepunkrock If it's still reproducible on latests versions - feel free to reopen

**Comment by Siemienik** [comment]
ExcelJS currently supports XLSX and CSV. I dream to add more formats, however, it is possible if I will get funds for this purpose.

**Comment by lmX2015** [comment]
TLDR, issue comes from the saxes library that has been used since 3.10.10 in replacement of sax-js. 

I encountered this issue too with latest release. Problem does not seems to be related to xlsm but rather to malformed xlm such as unclosed <br> tags, which is allowed by excel but not valid xml. 

Digging further, this is due to this [PR](https://github.com/exceljs/exceljs/pull/1127) (which explains why @vanyadymousky had only this problem starting at 3.10.0.

The PR itself is a migration of the XML parser from [sax-js ](https://github.com/isaacs/sax-js) that has been unmaintained for 6 years to [saxes](url), one of it forks which is faster, supports typescript and is currently maintained.  

The downside is that saxes has a different philosophy than sax regarding what it is supposed to parse. Saxes refuses to parse XML that is not strictly well formatted and throws error in this case, will sax had the "best effort" approach and tries to parse. For most XML files it doesn't make any difference, however excel is more permissive in terms of XML formatting, and accept some unclosed tags, including "<br>". 

I only see three options to fix that:
- reintegrate sax (even if it is used in complement of saxes, for non standard xml strings)
- fork sax to fix vulnerabilities, support typescript, improve speed etc.
- fork saxes to allow non standard XML to be parsed

While I could spend some times on one of these options, happy to have your opinions about it. 

Also for those who run a similar problem and want quick and dirty fix, a simple solution is to update your dependencies to use 3.9.0 an older version of exceljs.
