### ISSUE TITLE
[BUG] Conditional Formatting is changing the font to italics

### ISSUE THREAD

**Issue by dancolq** [exceljs/exceljs#1732]
## 🐛 Bug Report

When loading and saving an excel file with conditional formatting, the font style is changing

From this 
![image](https://user-images.githubusercontent.com/16645222/120246785-32871400-c269-11eb-86bf-2522b9613ab1.png)
To this
![image](https://user-images.githubusercontent.com/16645222/120246845-63ffdf80-c269-11eb-89f2-44c528666e14.png)

Lib version: 4.2.1

## Steps To Reproduce

1) Add conditional formatting 
![image](https://user-images.githubusercontent.com/16645222/120247026-061fc780-c26a-11eb-877b-589cfc902a0c.png)
2) With these styles
![image](https://user-images.githubusercontent.com/16645222/120247057-23ed2c80-c26a-11eb-86e8-3e84c24cdcff.png)
3) Make sure the cell matches the criteria and save
4) Load the excel workbook with excel.js
5) Export the excel workbook
6) The style has changed to Bold Italic

## The expected behaviour:

The font style of the conditional formatted cell should be the same style as the original workbook prior to excels loading it.

## Possible solution :
I'm not sure, although I must say that I'm grateful for the previous conditional formatting bug to have been fixed in the first place.

**Comment by sergeyampo** [comment]
I confirm that. If I set a rule style in conditional formatting, in debug mode I'll see that font style will be set like that:
worksheet.conditionalFormattings[i].rules[i].style.font.strike/bold/italic will be true but in the source excel file there will be a plain text.

**Comment by Codeneos** [comment]
I can confirm this as well and have tracked back the root cause of this to the way boolean are parsed in styles.xml/dxf. The solution is straightforward so I'll try creating a fix and PR for this later.

In summary when you create a conditional formatting rule with a new style an entry under created in styles.xml dxfs tag that looks like this:
```xml
 <dxfs count="1">
        <dxf>
            <font>
                <b val="0"/>
                <i/>
                <strike val="0"/>
                <color theme="0" tint="-0.499984740745262"/>
            </font>
            <fill>
                <patternFill patternType="none">
                    <fgColor indexed="64"/>
                    <bgColor auto="1"/>
                </patternFill>
            </fill>
        </dxf>
    </dxfs>
```

In this case I explicitly enabled all font styles closed the worksheet, re-opened it and disabled the font styles. Excel did not remove the `b` for bold and `strike` for strikethrough tags but instead set the `val` attr to 0. 

But the exceljs doesn't check the `val` attribute it just verifies the tag exists, if the tag is found it value is always true (hardcoded).
