### ISSUE TITLE
It is posible to insert rows between two others rows?

### ISSUE THREAD

**Issue by germanamz** [exceljs/exceljs#228]
What i want to achieve is to insert a row between row 17 & row 18 so the new row becomes the row 18

**Comment by alammfs** [comment]
I also need such a feature in this package

**Comment by sanderd17** [comment]
Should be possible since the addition of the splice functions since https://github.com/guyonroche/exceljs/commit/92a4f8a48e1bd27961a926e40c346660d2f93b7d 

See the `spliceRow` and `spliceColumn` functions in the docs, the signature is normally like this:
`spliceX(startNumber, rowsOrColsToDelete, dataToInsert, dataToInsert, ...)`

Though as I said in #265, meta data isn't updated in the same way as inserting a row in Excel functions. Only the values are shifted.

**Comment by cbeltrangomez84** [comment]
@optimistex why do you say it works wrong?

**Comment by optimistex** [comment]
@cbeltrangomez84 Never mind. I already can not remember what issues did I have 2 years ago )))

**Comment by cbeltrangomez84** [comment]
@optimistex Thanks.
@germanamz @Siemienik, could you close the issue? I have not permissions to do it.

Regards

**Comment by Siemienik** [comment]
This one should work fine, I am using it in several projects
if something wrong please correct me
