### ISSUE TITLE
[BUG] removeWorksheet is not a function when using a WorkbookWriter

### ISSUE THREAD

**Issue by fwoelffel** [exceljs/exceljs#2336]
## 🐛 Bug Report

Lib version: 4.3.0

## Steps To Reproduce

```javascript
const { PassThrough } = require('node:stream');

const wb = new Excel.stream.xlsx.WorkbookWriter({stream: new PassThrough()});
const ws = wb.addWorksheet('XYZ');
expect(() => wb.removeWorksheet(ws.id)).not.toThrow();
```

## The expected behaviour:

- Calling the `removeWorksheet` method of a `WorkbookWriter` should not throw
- **OR** the `WorkbookWriter` typings should be updated

## Possible solution (optional, but very helpful):

Remove the `Workbook` inheritance in the `WorkbookWriter` type declaration.

**Comment by dule-kitemetric** [comment]
It mays late but How had you solved this issue before?
Current i'm facing the same problem when using `WorkbookWriter`, there are many methods that can be used with WorkbookWriter.

I think it's because that when using WorkbookWriter, worksheets are written immediately to the stream and aren't kept in memory thus we can not modify written data.

**Comment by dule-kitemetric** [comment]
@fwoelffel 
It may late but How had you solved this issue before?
Current i'm facing the same problem when using `WorkbookWriter`, there are many methods that can not be used with WorkbookWriter.

I think it's because that when using WorkbookWriter, worksheets data are written immediately to the stream and aren't kept in memory thus we can not modify written data.

== **UPDATE**
Sorry my bad, this issue is about `type`, not about the functionality 😄

**Comment by fwoelffel** [comment]
I'm afraid I don't remember what I did regarding this issue ☹️ 

Are you certain you're facing the same issue? It's been closed as completed a while ago.

**Comment by dule-kitemetric** [comment]
> I'm afraid I don't remember what I did regarding this issue ☹️
> 
> Are you certain you're facing the same issue? It's been closed as completed a while ago.

Yes, it still happens when i use `exceljs` version `4.4.0`
It throws the below error when i call removeWorksheet method of WorkbookWriter although it's in the type haha

<img width="854" alt="image" src="https://github.com/user-attachments/assets/8771f701-d392-4908-a452-10b73ac8f8cd" />
