### ISSUE TITLE
excelJs crashes my Angular 2 Application

### ISSUE THREAD

**Issue by gentios** [exceljs/exceljs#303]
I have imported  "exceljs": "^0.4.3", in my angular 2 application and it crashes it, can you help me out to figure this issue ?

**Comment by guyonroche** [comment]
Can you reproduce this in a demo app?

**Comment by Alb0za** [comment]
we alerady made a fix, moved this task for the backend team with NodeJs

**Comment by dmr** [comment]
So the solution was to remove it from the angular-app, do I understand correctly?

**Comment by Alb0za** [comment]
@dmr , I was trying to import it to my Angular 2 application this module. Since it doesn't have typings, I tried to load it via webpack throught 

> /node_modules/exceljs/exceljs

, but that crashed my application, everything went blank, I searched a lot in the web and couldn't find a solution because poor documentation and so we moved this task to the back-end team, to handle they with nodejs, since this module gives full support for nodeJs.

the path that I took for importing this module:

at ```
angular-cli.json {
    "scripts": [
        "../node_modules/moment/moment.js",
        "../node_modules/exceljs/excel.js"
      ],
} 
```

and in my component:

`declare var ExcelJs: any;`

but this didn't work for me. It need typings to import it correctly for example:
`Import {ExcelJs} from 'exceljs';`
this is my opinion, hope anyone else has a better solution.

I am sorry for not providing a detailed information.
Best Regards

**Comment by guyonroche** [comment]
node_modules/exceljs/exceljs is for nodejs.
The one you would probably want is node_modules/exceljs/dist/exceljs.min.js -> this is the minified bundled file

**Comment by Alb0za** [comment]
@guyonroche  yes  I have used this one:

> node_modules/exceljs/dist/exceljs.min.js sorry that I have provided a wrong path

**Comment by ryanpm40** [comment]
Has anybody gotten this working? I've noticed that importing exceljs.min.js in index.html within <src> tags seems to cause angular apps to not load, but no console errors appear.

**Comment by Siemienik** [comment]
#348
