### ISSUE TITLE
autoFilter not applied properly

### ISSUE THREAD

**Issue by thecjharries** [exceljs/exceljs#400]
I'm using `0.5.1` against Excel 2010. I don't have access to 2013 or 365/2016 to verify the issue there as well. I have confirmed on both a VM and a physical install.

`sheet.autoFilter` doesn't work as intended. Using every method of setting the `autoFilter`, Excel crashes while trying to sort the data, i.e.
```javascript
// Excel crashes when attempting to use the filter
sheet.autoFilter = "A1:H1";
// Excel crashes when attempting to use the filter
sheet.autoFilter = {
    from: {
        column: 1,
        row: 3
    },
    to: {
        column: 9,
        row: 3
    }
};
```
However, clearing the `autoFilter` and reapplying through Excel, or ctrl+c/v the data into a fresh location then applying the filter does not crash Excel.

**Comment by thecjharries** [comment]
I was wrong; I have tested in 2013. 2010 crashes outright; 2013 hangs for an inordinate amount of time. Both happened with small sets (~10 rows) and larger sets (~200k rows)

**Comment by bill-griffin-aimia** [comment]
I had the same problem; Excel crashes when any attempt to sort the auto filter is used. I had the same problem with the js-xlsx library https://github.com/SheetJS/js-xlsx

I found a rather hacky workaround, and am posting it here in the hope that it may help someone else, or even prompt a more elegant solution, or better still, a fix to the exceljs code so that auto filtering works correctly.

The problem is that for Auto Filter Sorting to work, there must be a Defined Name. In this example, 2 Sheets, each with Auto Filtering:

```xml
<definedNames>
	<definedName hidden="1" localSheetId="0" name="_xlnm._FilterDatabase">Sheet1!$A$1:$B$3</definedName>
	<definedName hidden="1" localSheetId="1" name="_xlnm._FilterDatabase">Sheet2!$A$1:$B$3</definedName>
</definedNames>
```

I found that I could trick exceljs into writing these defined names as follows:

```javascript
    // Build up your Workbook as usual
    ...
    // Get the current definedNames model (in case you defined any):
    const model = workbook.definedNames.model;

    // Replace the 'model' getter and setter:
    Object.defineProperty(workbook.definedNames, 'model', {
      set: function(x) { this._model = x; },
      get: function() { return this._model; }
    });
    
    // Set the model property to your version:
    workbook.definedNames.model = [
      ...model,
      {name: '_xlnm._FilterDatabase', localSheetId: 0, hidden: 1, ranges: ['Sheet1!$A$1:$B$3']},
      {name: '_xlnm._FilterDatabase', localSheetId: 1, hidden: 1, ranges: ['Sheet2!$A$1:$B$3']}
    ];

    workbook.xlsx.writeBuffer()
```

This works for me, although the `hidden` attribute is not written to the XLSX file, and so I see the name '_filterDatabase' in Excel when I go to "Define Name".

**Comment by nglenno18** [comment]
Same issue here. When the number of rows is < 100, the sorting will work, but only once. The filter disappears off of the row.
