### ISSUE TITLE
row.commit nor worksheet.commit not saving anydata on filesystem

### ISSUE THREAD

**Issue by hamedebrahimi** [exceljs/exceljs#404]
I'm about to create 1m record xlsx file by this interface:
 new Exceljs.stream.xlsx.WorkbookWriter 

I'm getting out of memory exception by typical excels streaming approach and I'm committing in every row.commit and worksheet.commit but nothing save on filesystem unless i use workbook.commit....
how should i properly handle this situation?

**Comment by Blakey** [comment]
Share your code please, I have just implemented streaming exceljs and have no issues. Tested with 15 1,000,000 row spreadsheets streaming concurrently from SQL into Excel and did not have any memory issues and all files got generated.

**Comment by mfahmirukman** [comment]
@Blakey

Can you share me your code on how you'd write the xlsx file?

**Comment by longweiquan** [comment]
@Blakey @mfahmirukman ,

Hello, I encounter the same issue when i limit the memory. It throws exception at workbook.commit().  Here's my code :

``` index.js
const Excel = require('exceljs');

const start = new Date();
const options = {
  filename: './streamed-workbook.xlsx',
  useStyles: true,
  useSharedStrings: true
};
const workbook = new Excel.stream.xlsx.WorkbookWriter(options);
const worksheet = workbook.addWorksheet('Main');
for(let i = 1; i<= 800000; i++){
  worksheet.addRow([i, `firstName ${i}`, `lastName ${i}`]).commit();
}
worksheet.commit();
workbook.commit().then(function() {
  const end = new Date();
  console.log(`It takes ${end - start} milliseconds`);
});

// node --max-old-space-size=512 index.js
```

**Comment by mfahmirukman** [comment]
Okay, so I debugged on what's wrong with it.

Your Excel configuration uses useSharedStrings set as true
sharedStrings is a config that allows the same string to be used over and over again in many different cells. The problem lies when you set it as true, yet there's no same string anywhere.
if you go console.log(workbook.useSharedStrings); after your loop is finished, you'll see that you're actually saving over 1,600,000 strings.

I tried going with useSharedStrings: false, the memory usage jumped up to 200MB and immediately (after 16 seconds of writing), it dumped the memory and got back to 20-50MB ish.

**Comment by gsamal** [comment]
@mfahmirukman This does the trick for me! Thanks a lot!

I tried a lot of configuration yesterday with streams but no luck. It was bumping the memory when I commit the workbook. 
Quick question - When do you think we should use "useSharedString" and where can I see it's advantage? I suppose it's foolish to use this setting if you have 1M rows with unlikely same values, right?
