### ISSUE TITLE
Unsafe Eval in browser chrome extension

### ISSUE THREAD

**Issue by TomWagg** [exceljs/exceljs#512]
Hi,
I'm currently trying to use exceljs within a chrome extension and I am finding that if I get the js file from the dist folder then when I load it on the page, I get an error.
This error is from the chrome extension content security policy and seems to be stemming from a specific line that starts with
`var w,x=Array.prototype.slice,y=0,z=new Function`
Here the new Function appears to be disallowed by chrome due to a security issue by using a "non safe eval". Is there any way around this? I would love to be able to use exceljs in my extension!

**Comment by Deymoun** [comment]
Hi,
I try to load exceljs in a chrome extension which manifest version is 3.
However "content_security_policy" does not allow 'unsafe-eval' anymore.
So I get:
`exceljs.js:75243 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (<anonymous>)
    at Object.492 (exceljs.js:75243:3)
    at o (exceljs.js:1:632)
    at exceljs.js:1:683
    at Object.15../doc/enums (exceljs.js:5380:1)
    at o (exceljs.js:1:632)
    at r (exceljs.js:1:798)
    at exceljs.js:1:827
    at exceljs.js:1:317
    at exceljs.js:1:323`
Any idea?
Thank you!
