### ISSUE TITLE
workbook.xlsx.writeBuffer() function extremely slow in Internet Explorer 11

### ISSUE THREAD

**Issue by jgoris** [exceljs/exceljs#566]
I am using Angular 5 and have a fairly straightforward example of a spreadsheet that I am creating.  It is about 20 rows and 100 columns.  It works like a charm in Chrome, but when I test it in IE11 (unfortunately, IE is my company's standard browser), it is painfully slow.  It churns my CPU at about 35% for the entire time also, and my memory monitor fluxing up and down wildly.

My code to write on the client looks like this (I have seen this example many times in these issues discussions):

  wb.xlsx.writeBuffer().then( data => {
            const blob = new Blob( [data], { type: 'application/octet-stream'} );
            saveAs( blob, "myFile.xlsx");
   });

I am using the file-saver library and saveAs.  But the slow part is getting into the .then() of the writeBuffer() function.  In Chrome, getting into this callback is almost instantaneous while in IE it is over 35 seconds!
I have tried this on a couple of different Windows machines (7 and 10) and different hardware, with similar results.
Has anyone seen this behavior?

**Comment by Dalfons0** [comment]
Did you try the [msSaveAsBlob ](https://msdn.microsoft.com/en-us/library/hh772331(v=vs.85).aspx) method? Something like:
```
if (navigator.msSaveBlob) {
    navigator.msSaveBlob(blob, "myFile.xlsx");
} else {
    saveAs(blob, "myFile.xlsx");
}
```

**Comment by tosanjayrajpal** [comment]
I am also facing the same issue, workbook.xlsx.writeBuffer() takes a long time in Edge and Internet Explorer. In chrome, this works nicely.

@Dalfons0, we need to create blob first. Your solution assumes we already have a blob. But here the problem is we're not able to generate blob in IE and Edge browser.

Is there anything that we can pass to this method to behave differently?

Any help is highly apreciated. I've spent a lot of time on this, but with no success. This is really frustrating, please help.

Thanks
Sanjay
