### ISSUE TITLE
How can i load a xlsx file downloaded by url from browser?

### ISSUE THREAD

**Issue by Rockson** [exceljs/exceljs#592]
```ts
const wb2 = new ExcelJs.Workbook()
  
  const resp = await fetch(new Request("/file.xlsx"))

  const stream = resp.body!

  wb2.xlsx.read(stream).then(() => {
    const ws = wb2.getWorksheet(0)
    console.log(ws)
  })
```

it doesn't enter in the then callback, why?

**Comment by Rockson** [comment]
Ok i found the solution thanks to #539 :

```ts
const wb2 = new ExcelJs.Workbook()

  const resp = await fetch(new Request("/public.xlsx", ))

  const input: any = wb2.xlsx.createInputStream()
  const buff = await resp.arrayBuffer()

  const buffer = Buffer.from(buff)
  const readStream = new Stream.PassThrough()
  readStream.end(buffer)
  readStream.pipe(input)

  input.on("done", () => {
    console.log(wb2.getWorksheet(1))
  })
```

**Comment by cbeltrangomez84** [comment]
Thanks @Rockson 

Since createInputStream is deprecated this code works for me:

`const Excel = require('exceljs');
const stream = require('stream');

var workbook = new Excel.Workbook();
   const resp = await fetch(new Request("assets/file.xlsx"));
   const buff = await resp.arrayBuffer(); 
   const buffer = Buffer.from(buff)
   const readStream = new stream.PassThrough();
   readStream.end(buffer);
   const wb = await workbook.xlsx.read(readStream);`
