### ISSUE TITLE
Borders on empty cells

### ISSUE THREAD

**Issue by saadq** [exceljs/exceljs#82]
I'm trying to add borders on all cells, including empty ones. Here is the code I tried to use:

``` javascript
var borderStyles = {
  top: { style: "thin" },
  left: { style: "thin" },
  bottom: { style: "thin" },
  right: { style: "thin" }
};

worksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
  row.eachCell({ includeEmpty: true }, function(cell, colNumber) {
    cell.border = borderStyles;
  });
});
```

I thought that using `{ includeEmpty: true }` would do this for me, but it doesn't seem to work, as you can see here:

![screen shot 2016-03-11 at 9 00 02 pm](https://cloud.githubusercontent.com/assets/5678694/13719995/87feb640-e7cc-11e5-8c23-e4742dd04bda.png)

I want the gaps in between the sections to have borders as well. I made those gaps by doing `addRow` and passing it an empty object `{}`, could that be causing an issue?

 Or is there any other way to get borders to appear on all cells?

**Comment by EdonGashi** [comment]
I am facing the same problem... I found a workaround by placing empty strings to force values on cells. It works this way, although it's causing me trouble with cell merging in MS Excel

if (!cell.value) {
    cell.value = '';
}

**Comment by saadq** [comment]
Yup, that's the workaround I went with as well. Not very pretty, but it worked :/

And yeah, I didn't have to do any cell merging but I see how that would be an issue

**Comment by MegazeroMZ** [comment]
So... any update on this problem? I'm trying to create border on empty cells too and I cant do it :( (Without using the trick of adding '' character)

**Comment by HankMcCoy** [comment]
I managed to get this working by tweaking the code locally. I hope to get a PR open by mid next week.

The basic problem is that there are several places in the codebase where it checks to see if a cell has a type of `Enum.ValueType.Null` and if it does, it doesn't include it in the final render, presumably as an optimization. This is, of course, problematic when that cell still have styles applied to it, despite being empty.

The short summary of my local changes is that I:
* Removed the `if (cell.type != Enum.ValueType.Null)` check in the `get model()` accessor in `row.js`
* Removed the `spans="<%=row.min%>:<%=row.max">` attribute in the row section of `sheet.xml` since I had a hard time getting the min and max there to actually work ([spans](http://webapp.docx4java.org/OnlineDemo/ecma376/SpreadsheetML/row_1.html) is an optional optimization attribute anyway).
* Added a `default:` case to the `switch (cell.type)` statement in `xlsx.js` to do the same thing it was already doing for `case Enums.ValueType.Merge`.

**Comment by rabbishuki** [comment]
Found a better way.

Instead of using:
```
worksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
  row.eachCell({ includeEmpty: true }, function(cell, colNumber) {
    cell.border = borderStyles;
  });
});
```
Try using it like this:
```
worksheet.eachRow({ includeEmpty: true }, function(row, rowNumber) {
  row.border = borderStyles;
});
```
As a bonus it is probably faster because you are only setting one property instead of iterating of all the cells.

**Comment by Avasse** [comment]
Any news on "Setting borders on empty cells" ? 
Found nothing new except above PR but still having the same issue

**Comment by justanintrovert** [comment]
this worked for me. It will set the border for the specific data table.

```
        worksheet.eachRow((cell, rowNumber) => {
            worksheet.getRow(rowNumber).eachCell({includeEmpty:true}, (cell_v, colNumber) => {
                if(colNumber <= worksheet.columnCount) {
                    cell_v.border = this.borderStyles;
                }
            })            
        })
```
