### ISSUE TITLE
Data Validation (Allow Positive number Only)

### ISSUE THREAD

**Issue by sumitbhavra** [exceljs/exceljs#998]
Hi, I am having trouble with the data validation part. How can I make users only enter a positive integer or decimal numbers in a column? Could you please explain the data validation part?

const numberValidator = () => {
  ws.getCell(cell).dataValidation = {
    type: 'decimal',
    allowBlank: true,
    showErrorMessage: true,
    showInputMessage: true,
    promptTitle: 'Decimal',
    prompt: `Note: Metric Calculated Value should come between ${min}-${max}`,
    error: 'Please provide numeric value.',
  };
};

Regards
Sumit

**Comment by guyonroche** [comment]
@sumitbhavra you want to add an operator and formulae result to constrain the valid values. The documentation has some examples: [https://github.com/exceljs/exceljs#data-validations](https://github.com/exceljs/exceljs#data-validations)

**Comment by jeffpohlmeyer** [comment]
Since you're using a min and max in your string you'd want something like this.

const numberValidator = (min, max) => {
  ws.getCell(cell).dataValidation = {
    type: 'decimal',
    operator: 'between',
    formulae: [min, max],
    allowBlank: true,
    showErrorMessage: true,
    showInputMessage: true,
    promptTitle: 'Decimal',
    prompt: `Note: Metric Calculated Value should come between ${min}-${max}`,
    error: 'Please provide numeric value.',
  };
};


If you want just positive numbers only then you'll update your prompt, not pass in any arguments to numberValidator, change the operator to be 'greaterThan' and change the formulae to be [0]

**Comment by sumitbhavra** [comment]
thanks. this was addressed earlier. Anyway, thanks for the info
